/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-ep.ts
 */

export const EP = {
  global: {
    health: () => `/v1/global/health-check`,
  },
  auth: {
    exchange: () => `/v1/auth/exchange`,
    logout: () => `/v1/auth/logout`,
    reissue: () => `/v1/auth/reissue`,
  },
  user: {
    agreement: () => `/v1/user/agreement`,
    updateProfile: () => `/v1/user/me/profile`,
  },
  album: {
    create: () => `/v1/album`,
    availableCount: (code: string) => `/v1/album/${code}/available-count`,
    enter: (code: string) => `/v1/album/${code}/enter`,
    invitation: (code: string) => `/v1/album/${code}/invitation`,
    participants: (code: string) => `/v1/album/${code}/participants`,
    photos: (code: string) => `/v1/album/${code}/photos`,
    photoDetail: (code: string, photoId: number) => `/v1/album/${code}/photos/${photoId}`,
    likedPhotos: (code: string) => `/v1/album/${code}/photos/liked`,
  },
  photo: {
    like: (photoId: number) => `/v1/photo/${photoId}/liked`,
    unlike: (photoId: number) => `/v1/photo/${photoId}/unliked`,
    presignedDownload: () => `/v1/photo/download-url`,
    presignedUpload: () => `/v1/photo/presigned-url`,
    reportUploadResult: () => `/v1/photo/report`,
  },
  cheese4cut: {
    finalize: (code: string) => `/v1/cheese4cut/${code}/fixed`,
    presignedUpload: (code: string) => `/v1/cheese4cut/${code}/presigned-url`,
    preview: (code: string) => `/v1/cheese4cut/${code}/preview`,
  },
  internal: {
    thumbnailComplete: () => `/internal/thumbnail/complete`,
  }
} as const;

// 선택지 Enum(정렬)
export type PhotoSorting = 'POPULAR' | 'CAPTURED_AT' | 'CREATED_AT';
