/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-ep.ts
 */

export const EP = {
  global: {
    health: () => `/v1/global/health-check`,
  },
  auth: {
    exchange: () => `/v1/auth/exchange`,
    logout: () => `/v1/auth/logout`,
    reissue: () => `/v1/auth/reissue`,
  },
  user: {
    agreement: () => `/v1/user/agreement`,
    updateProfile: () => `/v1/user/me/profile`,
  },
  album: {
    create: () => `/v1/album`,
    availableCount: (code: string) => `/v1/album/${code}/available-count`,
    enter: (code: string) => `/v1/album/${code}/enter`,
    invitation: (code: string) => `/v1/album/${code}/invitation`,
    participants: (code: string) => `/v1/album/${code}/participants`,
    photos: (code: string) => `/v1/album/${code}/photos`,
    photoDetail: (code: string, photoId: number) => `/v1/album/${code}/photos/${photoId}`,
    likedPhotos: (code: string) => `/v1/album/${code}/photos/liked`,
  },
  photo: {
    like: (photoId: number) => `/v1/photo/${photoId}/liked`,
    unlike: (photoId: number) => `/v1/photo/${photoId}/unliked`,
    presignedDownload: () => `/v1/photo/download-url`,
    presignedUpload: () => `/v1/photo/presigned-url`,
    reportUploadResult: () => `/v1/photo/report`,
  },
  cheese4cut: {
    finalize: (code: string) => `/v1/cheese4cut/${code}/fixed`,
    presignedUpload: (code: string) => `/v1/cheese4cut/${code}/presigned-url`,
    preview: (code: string) => `/v1/cheese4cut/${code}/preview`,
  },
  internal: {
    thumbnailComplete: () => `/internal/thumbnail/complete`,
  }
} as const;

// 선택지 Enum(정렬)
export type PhotoSorting = 'POPULAR' | 'CAPTURED_AT' | 'CREATED_AT';

/* =======================
 * Generated Types
 * ======================= */

// --- Components
export interface UserAgreementRequestSchema { "isServiceAgreement": boolean; "isUserInfoAgreement": boolean; "isMarketingAgreement"?: boolean; "isThirdPartyAgreement"?: boolean; }
export interface CommonResponseVoidSchema { "isSuccess"?: boolean; "code"?: number; "message"?: string; "result"?: unknown; }
export interface PhotoUploadReportRequestSchema { "failurePhotoIds": number[]; }
export interface FileInfoSchema { "fileName": string; "fileSize"?: number; "contentType": string; }
export interface PhotoPresignedUrlRequestSchema { "albumCode": string; "fileInfos": FileInfoSchema[]; }
export interface CommonResponsePhotoPresignedUrlResponseSchema { "isSuccess"?: boolean; "code"?: number; "message"?: string; "result"?: PhotoPresignedUrlResponseSchema; }
export interface PhotoPresignedUrlResponseSchema { "presignedUrlInfos"?: PresignedUrlInfoSchema[]; }
export interface PresignedUrlInfoSchema { "photoId"?: number; "uploadUrl"?: string; }
export interface PhotoDownloadRequestSchema { "code"?: string; "photoIds"?: number[]; }
export interface CommonResponsePhotoDownloadResponseSchema { "isSuccess"?: boolean; "code"?: number; "message"?: string; "result"?: PhotoDownloadResponseSchema; }
export interface DownloadFileInfoSchema { "photoId"?: number; "downloadUrl"?: string; "fileName"?: string; "captureTime"?: string; "createdAt"?: string; }
export interface PhotoDownloadResponseSchema { "downloadFiles"?: DownloadFileInfoSchema[]; }
export interface Cheese4cutPresignedUrlResponseSchema { "uploadUrl"?: string; }
export interface CommonResponseCheese4cutPresignedUrlResponseSchema { "isSuccess"?: boolean; "code"?: number; "message"?: string; "result"?: Cheese4cutPresignedUrlResponseSchema; }
export interface Cheese4cutFixedRequestSchema { "photoIds": number[]; }
export interface AuthReissueRequestSchema { "refreshToken"?: string; }
export interface AuthReissueResponseSchema { "accessToken"?: string; "refreshToken"?: string; }
export interface CommonResponseAuthReissueResponseSchema { "isSuccess"?: boolean; "code"?: number; "message"?: string; "result"?: AuthReissueResponseSchema; }
export interface AlbumCreationRequestSchema { "themeEmoji"?: string; "title"?: string; "participant"?: number; "eventDate"?: string; }
export interface AlbumCreationResponseSchema { "themeEmoji"?: string; "title"?: string; "eventDate"?: string; "currentPhotoCnt"?: number; "code"?: string; }
export interface CommonResponseAlbumCreationResponseSchema { "isSuccess"?: boolean; "code"?: number; "message"?: string; "result"?: AlbumCreationResponseSchema; }
export type AlbumEnterResponseSchema = unknown;
export interface AlbumMakerInfoSchema { "makerName"?: string; "makerProfileImage"?: string; }
export interface CommonResponseAlbumEnterResponseSchema { "isSuccess"?: boolean; "code"?: number; "message"?: string; "result"?: ExistingEnterResponseSchema | NewEnterResponseSchema; }
export type ExistingEnterResponseSchema = AlbumEnterResponseSchema & { "joinStatus"?: "NEW" | "EXISTING" | "REJOINED"; "title"?: string; "themeEmoji"?: string; "eventDate"?: string; "expiredAt"?: string; "makerInfo"?: AlbumMakerInfoSchema; };
export type NewEnterResponseSchema = AlbumEnterResponseSchema & { "joinStatus"?: "NEW" | "EXISTING" | "REJOINED"; "title"?: string; "themeEmoji"?: string; "eventDate"?: string; "expiredAt"?: string; "makerInfo"?: AlbumMakerInfoSchema; "remainingUploadSlots"?: number; "recentPhotos"?: RecentPhotoResponseSchema; };
export interface RecentPhotoResponseSchema { "thumbnailUrl": string; "uploaderName": string; "uploaderProfileImage": string; }
export interface PhotoCompleteRequestSchema { "photoId": number; "thumbnailUrl": string; }
export interface UserProfileRequestSchema { "name"?: string; }
export interface CommonResponseStringSchema { "isSuccess"?: boolean; "code"?: number; "message"?: string; "result"?: string; }
export type Cheese4cutFinalResponseSchema = Cheese4cutResponseSchema & { "isFinalized"?: boolean; };
export type Cheese4cutPreviewResponseSchema = Cheese4cutResponseSchema & { "isFinalized"?: boolean; "previewPhotos"?: PreviewPhotoInfoSchema[]; "uniqueLikesCount"?: number; "participant"?: number; };
export interface Cheese4cutResponseSchema { "finalized"?: boolean; }
export interface CommonResponseCheese4cutResponseSchema { "isSuccess"?: boolean; "code"?: number; "message"?: string; "result"?: Cheese4cutFinalResponseSchema | Cheese4cutPreviewResponseSchema; }
export interface PreviewPhotoInfoSchema { "photoId"?: number; "imageUrl"?: string; }
export interface AuthExchangeResponseSchema { "accessToken"?: string; "refreshToken"?: string; "isOnboarded"?: boolean; "userId"?: number; "name"?: string; "email"?: string; }
export interface CommonResponseAuthExchangeResponseSchema { "isSuccess"?: boolean; "code"?: number; "message"?: string; "result"?: AuthExchangeResponseSchema; }
export interface CommonResponsePhotoPageResponseSchema { "isSuccess"?: boolean; "code"?: number; "message"?: string; "result"?: PhotoPageResponseSchema; }
export interface PhotoListResponseSchema { "photoId"?: number; "thumbnailUrl"?: string; "likeCnt"?: number; "isLiked"?: boolean; "isDownloaded"?: boolean; "isRecentlyDownloaded"?: boolean; }
export interface PhotoPageResponseSchema { "responses"?: PhotoListResponseSchema[]; "listSize"?: number; "isFirst"?: boolean; "isLast"?: boolean; "hasNext"?: boolean; }
export interface CommonResponsePhotoDetailResponseSchema { "isSuccess"?: boolean; "code"?: number; "message"?: string; "result"?: PhotoDetailResponseSchema; }
export interface PhotoDetailResponseSchema { "name"?: string; "photoId"?: number; "imageUrl"?: string; "thumbnailUrl"?: string; "likesCnt"?: number; "isLiked"?: boolean; "isDownloaded"?: boolean; "isRecentlyDownloaded"?: boolean; }
export interface CommonResponsePhotoLikedPageResponseSchema { "isSuccess"?: boolean; "code"?: number; "message"?: string; "result"?: PhotoLikedPageResponseSchema; }
export interface PhotoLikedPageResponseSchema { "responses"?: PhotoLikedResponseSchema[]; "listSize"?: number; "isFirst"?: boolean; "isLast"?: boolean; "hasNext"?: boolean; }
export interface PhotoLikedResponseSchema { "photoId"?: number; "thumbnailUrl"?: string; "isDownloaded"?: boolean; "isRecentlyDownloaded"?: boolean; }
export interface AlbumParticipantResponseSchema { "isExpired"?: boolean; "title"?: string; "themeEmoji"?: string; "eventDate"?: string; "expiredAt"?: string; "maxParticipantCount"?: number; "currentParticipantCount"?: number; "participants"?: ParticipantInfoSchema[]; "myRole"?: "MAKER" | "GUEST" | "BLACK"; }
export interface CommonResponseAlbumParticipantResponseSchema { "isSuccess"?: boolean; "code"?: number; "message"?: string; "result"?: AlbumParticipantResponseSchema; }
export interface ParticipantInfoSchema { "name"?: string; "profileImage"?: string; "role"?: "MAKER" | "GUEST" | "BLACK"; "isMe"?: boolean; }
export interface AlbumInvitationResponseSchema { "title"?: string; "themeEmoji"?: string; "eventDate"?: string; "expiredAt"?: string; "makerName"?: string; "makerProfileImage"?: string; "isExpired"?: boolean; }
export interface CommonResponseAlbumInvitationResponseSchema { "isSuccess"?: boolean; "code"?: number; "message"?: string; "result"?: AlbumInvitationResponseSchema; }
export interface CommonResponseUploadAvailableCountResponseSchema { "isSuccess"?: boolean; "code"?: number; "message"?: string; "result"?: UploadAvailableCountResponseSchema; }
export interface UploadAvailableCountResponseSchema { "availableCount"?: number; "maxPhotoCount"?: number; "currentPhotoCount"?: number; }

// --- Operation Response Types
export type GlobalHealthResponse = CommonResponseStringSchema["result"];
export type AuthExchangeResponse = CommonResponseAuthExchangeResponseSchema["result"];
export type AuthLogoutResponse = CommonResponseVoidSchema["result"];
export type AuthReissueResponse = CommonResponseAuthReissueResponseSchema["result"];
export type UserAgreementResponse = CommonResponseVoidSchema["result"];
export type UserUpdateProfileResponse = CommonResponseVoidSchema["result"];
export type AlbumCreateResponse = CommonResponseAlbumCreationResponseSchema["result"];
export type AlbumAvailableCountResponse = CommonResponseUploadAvailableCountResponseSchema["result"];
export type AlbumEnterResponse = CommonResponseAlbumEnterResponseSchema["result"];
export type AlbumInvitationResponse = CommonResponseAlbumInvitationResponseSchema["result"];
export type AlbumParticipantsResponse = CommonResponseAlbumParticipantResponseSchema["result"];
export type AlbumPhotosResponse = CommonResponsePhotoPageResponseSchema["result"];
export type AlbumPhotoDetailResponse = CommonResponsePhotoDetailResponseSchema["result"];
export type AlbumLikedPhotosResponse = CommonResponsePhotoLikedPageResponseSchema["result"];
export type PhotoLikeResponse = CommonResponseVoidSchema["result"];
export type PhotoUnlikeResponse = CommonResponseVoidSchema["result"];
export type PhotoPresignedDownloadResponse = CommonResponsePhotoDownloadResponseSchema["result"];
export type PhotoPresignedUploadResponse = CommonResponsePhotoPresignedUrlResponseSchema["result"];
export type PhotoReportUploadResultResponse = CommonResponseVoidSchema["result"];
export type Cheese4cutFinalizeResponse = CommonResponseVoidSchema["result"];
export type Cheese4cutPresignedUploadResponse = CommonResponseCheese4cutPresignedUrlResponseSchema["result"];
export type Cheese4cutPreviewResponse = CommonResponseCheese4cutResponseSchema["result"];
export type InternalThumbnailCompleteResponse = CommonResponseVoidSchema["result"];

// --- Mapping: 'group.fn' -> Response Type
export interface ApiReturns {
  "global.health": GlobalHealthResponse; // GET /v1/global/health-check
  "auth.exchange": AuthExchangeResponse; // GET /v1/auth/exchange
  "auth.logout": AuthLogoutResponse; // POST /v1/auth/logout
  "auth.reissue": AuthReissueResponse; // POST /v1/auth/reissue
  "user.agreement": UserAgreementResponse; // POST /v1/user/agreement
  "user.updateProfile": UserUpdateProfileResponse; // PATCH /v1/user/me/profile
  "album.create": AlbumCreateResponse; // POST /v1/album
  "album.availableCount": AlbumAvailableCountResponse; // GET /v1/album/{code}/available-count
  "album.enter": AlbumEnterResponse; // POST /v1/album/{code}/enter
  "album.invitation": AlbumInvitationResponse; // GET /v1/album/{code}/invitation
  "album.participants": AlbumParticipantsResponse; // GET /v1/album/{code}/participants
  "album.photos": AlbumPhotosResponse; // GET /v1/album/{code}/photos
  "album.photoDetail": AlbumPhotoDetailResponse; // GET /v1/album/{code}/photos/{photoId}
  "album.likedPhotos": AlbumLikedPhotosResponse; // GET /v1/album/{code}/photos/liked
  "photo.like": PhotoLikeResponse; // POST /v1/photo/{photoId}/liked
  "photo.unlike": PhotoUnlikeResponse; // DELETE /v1/photo/{photoId}/unliked
  "photo.presignedDownload": PhotoPresignedDownloadResponse; // POST /v1/photo/download-url
  "photo.presignedUpload": PhotoPresignedUploadResponse; // POST /v1/photo/presigned-url
  "photo.reportUploadResult": PhotoReportUploadResultResponse; // POST /v1/photo/report
  "cheese4cut.finalize": Cheese4cutFinalizeResponse; // POST /v1/cheese4cut/{code}/fixed
  "cheese4cut.presignedUpload": Cheese4cutPresignedUploadResponse; // POST /v1/cheese4cut/{code}/presigned-url
  "cheese4cut.preview": Cheese4cutPreviewResponse; // GET /v1/cheese4cut/{code}/preview
  "internal.thumbnailComplete": InternalThumbnailCompleteResponse; // POST /internal/thumbnail/complete
}
