export const GA_EVENTS = {
  complete_login: 'complete_login',
  complete_signup: 'complete_signup',
  click_login: 'click_login',
  complete_album_joined: 'complete_album_joined',
  view_landing: 'view_landing',
  view_album: 'view_album',
  view_invited: 'view_invited',
  view_login: 'view_login',
  view_albumsidebar: 'view_albumsidebar',
  click_invite: 'click_invite',
  click_invite_complete: 'click_invite_complete',
  click_create_4cut: 'click_create_4cut',
  click_create_4cut_complete: 'click_create_4cut_complete',
  click_download_4cut: 'click_download_4cut',
  click_share_4cut: 'click_share_4cut',
  click_request_4cut: 'click_request_4cut',
  view_4cut_unconfirmed: 'view_4cut_unconfirmed',
  view_4cut_confirmed: 'view_4cut_confirmed',
  rendering_slide_view: 'rendering_slide_view',
  cta_click: 'cta_click',
};
